// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AnimationBg: typeof import('./src/components/animationBg.vue')['default']
    ArticleHead: typeof import('./src/components/ArticleHead.vue')['default']
    CommonContent: typeof import('./src/components/commonContent.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FixedButton: typeof import('./src/components/FixedButton.vue')['default']
    ForecastCard: typeof import('./src/components/ForecastCard.vue')['default']
    Menu: typeof import('./src/components/menu.vue')['default']
  }
}

export { }
